import {Appointment} from '../models/Appointment.js'; import {Doctor} from '../models/Doctor.js'; import {Patient} from '../models/Patient.js'; import type {AppointmentStatus} from '../types/domain.js'; import {toZonedTime} from 'date-fns-tz';
const finalStatuses=new Set<AppointmentStatus>(['realizada','falta','cancelada_paciente','cancelada_clinica']);
const allowed:Record<AppointmentStatus,AppointmentStatus[]>={agendada:['confirmada','realizada','falta','cancelada_paciente','cancelada_clinica'],confirmada:['realizada','falta','cancelada_paciente','cancelada_clinica'],realizada:[],falta:[],cancelada_paciente:[],cancelada_clinica:[]};
const dayMap=['domingo','segunda','terca','quarta','quinta','sexta','sabado'];
export async function createAppointment(input:{patientId:string;doctorId:string;appointmentAt:Date;attendanceType:'convenio'|'particular'}){
 const [doctor,patient]=await Promise.all([Doctor.findOne({externalId:input.doctorId}),Patient.findOne({externalId:input.patientId})]); if(!doctor||!patient) throw new Error('Médico ou paciente não encontrado.');
 const local=toZonedTime(input.appointmentAt,'America/Sao_Paulo'); if(local.getMinutes()%30!==0) throw new Error('A consulta deve iniciar em slot de 30 minutos.'); const hm=`${String(local.getHours()).padStart(2,'0')}:${String(local.getMinutes()).padStart(2,'0')}`; const day=dayMap[local.getDay()]; const inside=doctor.grade.some((g:any)=>g.dia===day&&hm>=g.inicio&&hm<g.fim); if(!inside) throw new Error('Horário fora da grade do médico.');
 const conflict=await Appointment.findOne({appointmentAt:input.appointmentAt,status:{$in:['agendada','confirmada']},$or:[{doctorId:input.doctorId},{patientId:input.patientId}]}); if(conflict) throw new Error('Médico ou paciente já possui consulta nesse horário.');
 return Appointment.create({...input,patientName:patient.nome,patientPhone:patient.telefone,bookedAt:new Date(),status:'agendada',source:'system'});
}
export async function changeStatus(id:string,next:AppointmentStatus){const appt=await Appointment.findById(id); if(!appt) throw new Error('Consulta não encontrada.'); const current=appt.status as AppointmentStatus; if(finalStatuses.has(current)||!allowed[current].includes(next)) throw new Error(`Transição inválida: ${current} -> ${next}.`); const now=new Date(); if(['realizada','falta'].includes(next)&&now<appt.appointmentAt) throw new Error('Realizada/falta só podem ser registradas após o horário.'); if(next.startsWith('cancelada')&&now>=appt.appointmentAt) throw new Error('Cancelamento só pode ser registrado antes da consulta.'); if(next==='cancelada_paciente'){const diff=(appt.appointmentAt.getTime()-now.getTime())/36e5; if(diff<1){appt.lateCancellation=true; appt.penalty=true;}} appt.status=next; await appt.save(); return appt;}
